version: "3.1"
services:
  rasa_core:
    image: rasa/rasa:latest
    volumes:
      - ./:/app
    ports:
      - "5005:5005"
    command: "run --enable-api --debug"
    depends_on:
      - rasa_action_server

  rasa_action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command: "run actions"
